version: "3.7"
services:

#  gin-srv:
#    image: golang:latest
#    environment:
#      GOPROXY: https://goproxy.cn,direct
#    volumes:
#      - "$PWD/:/app"
#    working_dir: "/app"
#    ports:
#      - "5000:5000"
#    command: "go run ."
#    container_name: "gin"
#    depends_on:
#      - mysql-srv

  mysql-srv:
    image: mysql:8.0
    restart: always
    container_name: "gin-mysql"
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    volumes:
      - "$PWD/tmp/mysql/my.cnf:/root/.my.cnf:ro"
      - "$PWD/tmp/mysql/conf.d:/etc/mysql/conf.d:ro"
      - "$PWD/tmp/mysql/logs:/var/log/mysql:rw"
      - "$PWD/tmp/mysql/initdb.d:/docker-entrypoint-initdb.d:ro"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lin-cms
      MYSQL_USER: root
      MYSQL_PASSWORD: root